version: 2

sources:
  - name: staging
    database: lucid-volt-375207
    schema: trips_data_all

  tables:
    - name: green_tripdata_external
    - name: yellow_tripdata_external
    - name: fhv_tripdata_external

  

